#Snakemake configuration file

#this file contains the info specific to a snakemake run

#project directory this ine needs to be changed
proj_dir: /project2/gilad/spott/drop_test

#logfile
dir_log: /project2/gilad/spott/drop_test/log/
#Genome index for STAR aligner
genome_index: /project2/gilad/spott/Pipelines/dropseq_pipeline/STAR_indeces/hg38_noalt_juncGencodeV27_49/

#transcript file
txn_file: /project2/gilad/spott/Pipelines/dropseq_pipeline/STAR_indeces/hg38_UCSC/gencode.v27.annotation.gtf

#feature file
#feature_file: /project2/basu/onibasu/data/

#expected number of cells the value is the upper bound, at least 10% of this value will be lower bound so make sure to adjust it
cell_num: 3000
# cell barcode UMI Configuration
barcode: "CCCCCCCCCCCCNNNNNNNN"
